services:
  tts:
    volumes:
      - ./.tts:/root/.local/share/tts
      - ./tts-server:/app
    platform: linux/amd64
    build:
      context: tts-server
      dockerfile: ../docker/tts/Dockerfile
    ports:
      - "8081:8080"
  wojciech-bot-dev:
    command: sh -c "go run wojciech-bot/main.go"
    image: letigo-discord-bots-base:latest
    volumes:
      - ./:/app:cached
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./wojciech-bot/.env
  wojciech-bot-prod:
    restart: always
    environment:
      GO_ENV: production
      GIN_MODE: release
    env_file:
      - wojciech-bot/.env
    image: schemik/letigo-discord-bots-wojciech:latest
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./wojciech-bot/cookies.txt:/app/cookies.txt
  dev:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    volumes:
      - ./:/workspaces:cached
    command: sleep infinity
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
