services:
  tts:
    volumes:
      - ./.tts:/root/.local/share/tts
      - ./tts-server:/app
    platform: linux/amd64
    build:
      context: tts-server
      dockerfile: ../docker/tts/Dockerfile
    ports:
      - "8081:8080"
  dev:
    command: sh -c "go run src/main.go"
    image: letigo-discord-bots-base:latest
    volumes:
      - ./:/app:cached
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prod:
    restart: always
    environment:
      GO_ENV: production
      GIN_MODE: release
    env_file:
      - .env
    image: schemik/letigo-discord-bots:latest
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
  devcontainer:
    image: letigo-discord-bots-base:latest
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
