services:
  tts:
    volumes:
      - ./.tts:/root/.local/share/tts
      - ./tts-server:/app
    platform: linux/amd64
    build:
      context: tts-server
      dockerfile: ../docker/tts/Dockerfile
    ports:
      - "8081:8080"
  dev:
    build:
     context: .
     dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
