name: Publish image to docker registry
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/server/Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/letigo-discord-bots:latest .
          docker push ${{ vars.DOCKERHUB_USERNAME }}/letigo-discord-bots:latest

      - name: Push with tag
        if: github.event_name == 'release'
        run: |
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/letigo-discord-bots:lates ${{ vars.DOCKERHUB_USERNAME }}/letigo-discord-bots:${{github.event.release.tag_name}}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/letigo-discord-bots:${{github.event.release.tag_name}}
          
