name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((?!skip ci).)*$'
          flags: 's'
          error: 'Skipping for release commit.'

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install npm dependencies
        run: |
          npm ci && npm ci --prefix deploy

      - name: Build
        run: npm run build

      - name: Test
        run: npm run lint && npm run test
        env:
          DAILY_REPORT_CHANNEL_ID: ${{ secrets.DAILY_REPORT_CHANNEL_ID }}
          DAILY_REPORT_TARGET_USER_ID: ${{ secrets.DAILY_REPORT_TARGET_USER_ID }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
